### ISSUE TITLE
Only URLs are being color-converted

### ISSUE THREAD

**Issue by rEnr3n** [therynamo/color-links#16]
![screenshot_2018-03-17_11-04-57](https://user-images.githubusercontent.com/18730618/37551107-72d3cd9a-29d4-11e8-8d59-94027dbf99c9.png)

I set my color to red. I clicked the wikipedia page in the screenshot. The title doesn't change to my set color. Only the URL at the bottom does even though both of them are poined at the same link.

~~I tried it on youtube and since there are no URLs present on the page, there are no color changes.~~
Some links on youtube change color but some don't.

Can you make an option so that all other elements (including images) get converted to the set color?

**Comment by therynamo** [comment]
Hey @rEnr3n, sorry it took so long to look into this issue. I think this can be broken out into two different issues. 

> I set my color to red. I clicked the wikipedia page in the screenshot. The title doesn't change to my set color. Only the URL at the bottom does even though both of them are poined at the same link.

I'll mark this as a bug.

> Can you make an option so that all other elements (including images) get converted to the set color?

This would be more of a feature, and we could discuss what that might look like. Perhaps a good opportunity for a PR that demonstrates what you're looking for.

**Comment by therynamo** [comment]
Fixed! 

![image](https://user-images.githubusercontent.com/8508556/82161906-2f8bd200-9866-11ea-9a64-7930576e249b.png)


Once #29 is merged and published to the chrome store, you'll see the changes reflected. Thanks for the bug report!
